version: 2
jobs:
  build:
    working_directory: ~/repo/backend

    docker:
      - image: circleci/clojure:lein-2.9.1

    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein do test, uberjar

      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: target/kahvilat-backend.jar
          destination: uberjar
      #
      #
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
